export const pricingConfig = {
  plans: [
    {
      name: 'Gratuit',
      price: 0,
      currency: 'EUR',
      period: 'pour toujours',
      description: 'Parfait pour commencer',
      features: [
        '1 page Link in Bio',
        '5 QR codes',
        '10 liens courts',
        'Analytics de base',
        'Thèmes gratuits',
        'Support communautaire',
      ],
      limitations: [
        'Pas de domaines personnalisés',
        'Analytics limitées',
        'Pas de support prioritaire',
      ],
      buttonText: 'Créer mon compte gratuit',
      buttonVariant: 'outline' as const,
      popular: false,
    },
    {
      name: 'Pro',
      price: 9,
      currency: 'EUR',
      period: '/mois',
      description: 'Pour les créateurs de contenu',
      features: [
        'Pages Link in Bio illimitées',
        'QR codes illimités',
        'Liens courts illimités',
        'Analytics avancées',
        'Domaines personnalisés',
        'Thèmes premium',
        'Support prioritaire',
        'Export haute qualité',
        'A/B testing',
        'Géolocalisation',
      ],
      limitations: [],
      buttonText: 'Commencer l\'essai gratuit',
      buttonVariant: 'default' as const,
      popular: true,
    },
    {
      name: 'Enterprise',
      price: 29,
      currency: 'EUR',
      period: '/mois',
      description: 'Pour les équipes et entreprises',
      features: [
        'Tout du plan Pro',
        'Équipe illimitée',
        'API complète',
        'SSO',
        'Support dédié',
        'Formation personnalisée',
        'SLA garanti',
        'Audit de sécurité',
      ],
      limitations: [],
      buttonText: 'Contactez-nous',
      buttonVariant: 'outline' as const,
      popular: false,
    },
  ],
  features: {
    linkInBio: {
      free: '1 page',
      pro: 'Illimitées',
      enterprise: 'Illimitées',
    },
    qrCodes: {
      free: '5 codes',
      pro: 'Illimités',
      enterprise: 'Illimités',
    },
    shortLinks: {
      free: '10 liens',
      pro: 'Illimités',
      enterprise: 'Illimités',
    },
    analytics: {
      free: 'Basiques',
      pro: 'Avancées',
      enterprise: 'Avancées + API',
    },
    domains: {
      free: 'Non',
      pro: 'Oui',
      enterprise: 'Oui',
    },
    support: {
      free: 'Communautaire',
      pro: 'Prioritaire',
      enterprise: 'Dédié',
    },
  },
} as const;
