export const databaseSchema = {
  users: {
    id: 'uuid',
    email: 'text',
    full_name: 'text',
    avatar_url: 'text',
    created_at: 'timestamp',
    updated_at: 'timestamp',
    clerk_id: 'text',
    subscription_status: 'text',
    subscription_id: 'text',
    custom_domain: 'text',
  },
  profiles: {
    id: 'uuid',
    user_id: 'uuid',
    title: 'text',
    description: 'text',
    theme: 'jsonb',
    background_image: 'text',
    profile_image: 'text',
    is_active: 'boolean',
    slug: 'text',
    custom_domain: 'text',
    created_at: 'timestamp',
    updated_at: 'timestamp',
    view_count: 'integer',
    click_count: 'integer',
  },
  links: {
    id: 'uuid',
    profile_id: 'uuid',
    title: 'text',
    url: 'text',
    icon: 'text',
    order: 'integer',
    is_active: 'boolean',
    created_at: 'timestamp',
    updated_at: 'timestamp',
    click_count: 'integer',
  },
  qr_codes: {
    id: 'uuid',
    user_id: 'uuid',
    name: 'text',
    url: 'text',
    qr_code_data: 'text',
    design: 'jsonb',
    created_at: 'timestamp',
    updated_at: 'timestamp',
    scan_count: 'integer',
  },
  analytics: {
    id: 'uuid',
    profile_id: 'uuid',
    link_id: 'uuid',
    qr_code_id: 'uuid',
    event_type: 'text',
    user_agent: 'text',
    ip_address: 'text',
    country: 'text',
    city: 'text',
    referrer: 'text',
    created_at: 'timestamp',
  },
  subscriptions: {
    id: 'uuid',
    user_id: 'uuid',
    stripe_subscription_id: 'text',
    stripe_customer_id: 'text',
    status: 'text',
    plan: 'text',
    current_period_start: 'timestamp',
    current_period_end: 'timestamp',
    created_at: 'timestamp',
    updated_at: 'timestamp',
  },
} as const;
